"""reconfigured order and batch models

Revision ID: 3521a72acca9
Revises: 7e08aba4e375
Create Date: 2026-07-08 20:48:40.150218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3521a72acca9'
down_revision: Union[str, Sequence[str], None] = '7e08aba4e375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batches', 'batch_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_batches_id'), 'batches', ['id'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_orders_batch_id'), 'orders', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_batch_id'), table_name='orders')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_batches_id'), table_name='batches')
    op.alter_column('batches', 'batch_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
