"""updating batches table with customer_id

Revision ID: 5a08fa026406
Revises: 3521a72acca9
Create Date: 2026-08-15 17:40:48.456379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a08fa026406'
down_revision: Union[str, Sequence[str], None] = '3521a72acca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_batches_customer_id'), 'batches', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'batches', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(op.f('fk_orders_batch_id_batches'), 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_batch_id_batches', 'orders', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_batch_id_batches', 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_batch_id_batches'), 'orders', 'batches', ['batch_id'], ['id'])
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_index(op.f('ix_batches_customer_id'), table_name='batches')
    op.drop_column('batches', 'customer_id')
    # ### end Alembic commands ###
