"""fixed dropbox link column in batches

Revision ID: 7e08aba4e375
Revises: ae1a4b373bc2
Create Date: 2026-07-06 21:04:45.272668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e08aba4e375'
down_revision: Union[str, Sequence[str], None] = 'ae1a4b373bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batches', 'dropbox_link',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batches', 'dropbox_link',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
