"""add batches table, connect it to orders table

Revision ID: ae1a4b373bc2
Revises: d71276e54034
Create Date: 2026-07-06 21:01:18.036001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1a4b373bc2'
down_revision: Union[str, Sequence[str], None] = 'd71276e54034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(), nullable=False),
    sa.Column('dropbox_link', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_code')
    )
    op.add_column('orders', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_orders_batch_id_batches', 'orders', 'batches', ['batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_batch_id_batches', 'orders', type_='foreignkey')
    op.drop_column('orders', 'batch_id')
    op.drop_table('batches')
    # ### end Alembic commands ###
