name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync

      - name: Ruff format check
        run: uv run ruff format . --check

      - name: Ruff lint check
        run: uv run ruff check .

      - name: Ruff auto-fix preview
        run: uv run ruff check . --diff
